# Used only for the spark application name
appName: Map build (development)

# An HBase table name, or a parquet file of occurrence records
# Hint: Consider using a Hive CTAS query "STORED AS PARQUET" from occurrence_hdfs
# source: /user/hive/warehouse/tim.db/occurrence_map_source_tenth
source: dev_occurrence

# The base directory into which HFiles will be stored
targetDirectory: hdfs://nameservice1/tmp/tim_maps

# The max record count allowed before the view is built into a tile pyramid
tilesThreshold: 100000

# HBase details
hbase:
  scannerCaching: 10000
  zkQuorum: zk1.gbif-dev.org,zk2.gbif-dev.org,zk3.gbif-dev.org
  keySaltModulus: 10

# Applies only to those map views that have few enough records to be stored as features
pointFeatures:
  numTasks: 200 # controls the parallelism
  tableName: tim_test
  hfileCount: 32

# TilePyramid applies to views where there are more records than the tilesThreshold
# Notes:
#   For hfileCount > 32 you must use -Dhbase.mapreduce.bulkload.max.hfiles.perRegion.perFamily=XXX when bulk loading
tilePyramid:
  tableName: tim_test
  hfileCount: 100
  numPartitions: 200
  tileBufferSize: 64
  projections:
    # Web Mercator (i.e. like google maps)
    -  minZoom: 0
       maxZoom: 16
       tileSize: 512
       srs: EPSG:3857
    # WGS84 "unprojected"
    -  minZoom: 0
       maxZoom: 16
       tileSize: 512
       srs: EPSG:4326
    # North Pole LAEA (i.e. Arctic)
    -  minZoom: 0
       maxZoom: 16
       tileSize: 512
       srs: EPSG:3575
    # Antarctic Polar Stereographic (i.e. South pole)
    -  minZoom: 0
       maxZoom: 16
       tileSize: 512
       srs: EPSG:3031
